"""Markdown design report: requirement -> generated design -> review -> repairs."""

from __future__ import annotations

from pathlib import Path

from ratsnest.schemas import DesignSpec, EvaluationResult, RunRecord

_SEV_ICON = {"error": "❌", "warning": "⚠️", "info": "ℹ️"}


def render_report(
    evaluation: EvaluationResult,
    record: RunRecord | None = None,
    spec: DesignSpec | None = None,
) -> str:
    sc = evaluation.scorecard
    lines: list[str] = ["# RatsNest Design Report", ""]

    if spec is not None:
        lines += [
            "## Requirement",
            "",
            f"> {spec.requirement_text or '(structured spec)'}",
            "",
            f"- board family: linear regulator ({spec.input_voltage:g}V -> "
            f"{spec.output_voltage:g}V)",
            f"- indicator LED: {spec.led or 'none'}",
            "",
        ]

    lines += [
        "## Scorecard",
        "",
        f"| score | findings | suppressed | severity |",
        f"|---|---|---|---|",
        f"| **{sc.score}/100** | {sc.findings_total} | {sc.suppressed_total} "
        f"| {sc.severity_counts} |",
        "",
        f"strategy version: `{sc.strategy_version_id}`",
        "",
    ]

    pcb_files = sorted(Path(evaluation.project_dir).glob("*.kicad_pcb")) \
        if evaluation.project_dir else []
    if pcb_files:
        board_text = pcb_files[0].read_text(encoding="utf-8", errors="replace")
        lines += [
            "## Board",
            "",
            f"| footprints | routed segments | outline |",
            f"|---|---|---|",
            f"| {board_text.count('(footprint')} "
            f"| {board_text.count('(segment')} "
            f"| {'yes' if 'Edge.Cuts' in board_text else 'no'} |",
            "",
        ]

    actionable = [f for f in evaluation.findings if f.severity in ("error", "warning")]
    lines += ["## Findings", ""]
    if actionable:
        lines += ["| sev | rule | summary |", "|---|---|---|"]
        for f in actionable:
            summary = str((f.model_extra or {}).get("summary", ""))[:110]
            lines.append(f"| {_SEV_ICON.get(f.severity, '')} {f.severity} "
                         f"| {f.rule_id or f.detector} | {summary} |")
    else:
        lines.append("No error/warning findings — board is clean. ✅")
    lines.append("")

    infos = [f for f in evaluation.findings if f.severity == "info"]
    if infos:
        lines += ["<details><summary>Informational detections "
                  f"({len(infos)})</summary>", ""]
        for f in infos:
            summary = str((f.model_extra or {}).get("summary", ""))[:110]
            lines.append(f"- `{f.rule_id or f.detector}` {summary}")
        lines += ["", "</details>", ""]

    if record is not None and record.iterations:
        lines += ["## Repair loop", "",
                  f"run `{record.run_id}` — status **{record.status}**", "",
                  "| iteration | score | delta | ops | resolved |",
                  "|---|---|---|---|---|"]
        for it in record.iterations:
            ops = len(it.patch_plan.ops) if it.patch_plan else 0
            lines.append(f"| {it.iteration} | {it.scorecard.score} "
                         f"| {it.score_delta:+.1f} | {ops} "
                         f"| {len(it.resolved_findings)} |")
        lines.append("")
        for it in record.iterations:
            if it.patch_plan and it.patch_plan.rationale:
                lines.append(f"**Iteration {it.iteration} repairs:**")
                for fid, why in it.patch_plan.rationale.items():
                    lines.append(f"- `{fid}` — {why}")
                lines.append("")
        if record.escalation:
            lines += ["### Escalated to human review", "",
                      f"```\n{record.escalation}\n```", ""]

    lines += ["---",
              "*generated by RatsNest — evaluation engine: kicad-happy "
              f"(unforked, schema 1.3.x)*", ""]
    return "\n".join(lines)


def write_report(path: Path, evaluation: EvaluationResult,
                 record: RunRecord | None = None,
                 spec: DesignSpec | None = None) -> Path:
    path = Path(path)
    path.write_text(render_report(evaluation, record, spec), encoding="utf-8")
    return path
